### ISSUE TITLE
responsiveness

### ISSUE THREAD

**Issue by adityadewhy** [adityadewhy/Socials#1]
the bottom 3spiderman image basically breaks the site(overlaps the card, making it unusable) if viewed on mobiles. fix it in a way that it appears at the bottom(after scrolling).

**Comment by Phil94comp** [comment]
I just submitted a pull request. Please let me know if this matches the criteria or if I need to make any adjustments.

**Comment by adityadewhy** [comment]
fixed 758b432981644df1f853154dedd2cc56e98a4ff1
thanks
